import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from '../components/Banner'


const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* F4ABC4 */}
      {/* #5DADE2  */}
      {/* #40E0D0  */}
      <Banner />


    </div>
  )
}

export default Home
